Repository InnovaGameCreate/akumutogenjitsu, pull requests merged in 2025-04, with the labels that each got.

#26 chore: GitHubのPRのテンプレートを作成
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#28 chore: 勉強用フォルダの追加
  Assets/Scenes/Learning.meta
  Assets/Scenes/Learning/Ochi.meta
  Assets/Scenes/Learning/Yoshida.meta
Labels: chore

#29 chore: 勉強用のフォルダの再配置
  Assets/Learning.meta
  Assets/Learning/Azuma.meta
  Assets/Learning/Azuma/Scenes.meta
  Assets/Learning/Azuma/Script.meta
  Assets/Learning/Ochi.meta
  Assets/Learning/Ochi/Scenes.meta
  Assets/Learning/Ochi/Script.meta
  Assets/Learning/Yoshida.meta
  Assets/Learning/Yoshida/Scenes.meta
  Assets/Learning/Yoshida/Script.meta
Labels: chore

#30 Fix/text event
  Assets/Prefabs/GameScene/Text Event.meta
  Assets/Prefabs/GameScene/Text Event/TextPanel.prefab
  Assets/Prefabs/GameScene/Text Event/TextPanel.prefab.meta
  Assets/Scenes/DeveloppingScenes/TextEvent.unity
  Assets/Scripts/GameScene/Event/Text/TextController.cs
  Assets/Scripts/GameScene/Event/Text/TextController.cs.meta
  Assets/Scripts/GameScene/Event/Text/TextDisplay.cs
Labels: task

#33 feat: Enemyのアニメーションを実装したEnemyのPrefabを作成
  Assets/Prefabs/GameScene/Enemy.meta
  Assets/Prefabs/GameScene/Enemy/Enemy.prefab
  Assets/Prefabs/GameScene/Enemy/Enemy.prefab.meta
  Assets/Resources/Image/GameScene/Enemy.meta
  Assets/Resources/Image/GameScene/Enemy/Enemy.png
  Assets/Resources/Image/GameScene/Enemy/Enemy.png.meta
  Assets/Scenes/DeveloppingScenes/EnemyAnimation.unity
  Assets/Scenes/DeveloppingScenes/EnemyAnimation.unity.meta
  ProjectSettings/TagManager.asset
Labels: task

#37 feat: カメラにPixel Perfect Cameraを設定
  Assets/Scenes/DeveloppingScenes/Target/April.unity
Labels: task

#38 chore: issueのテンプレートを設定
  .github/ISSUE_TEMPLATE/01-default.yml
Labels: chore

#60 chore: PRのテンプレートを変更
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#61 feat: アイテムの取得イベント
  Assets/Scenes/DeveloppingScenes/Item.unity
  Assets/Scripts/GameScene/Event/AbstractEvent/AbstractEvent.cs
  Assets/Scripts/GameScene/Event/ItemEvent.cs
  Assets/Scripts/GameScene/Event/ItemEvent.cs.meta
  Assets/Scripts/GameScene/Event/eEvent.cs
  ProjectSettings/TagManager.asset
Labels: task, event, item
